USE NORTHWIND;
GO
SELECT 
	(SELECT CONCAT(E.LASTNAME, E.FIRSTNAME) 
    FROM DBO.EMPLOYEES AS E
	WHERE E.EMPLOYEEID = O.EMPLOYEEID) AS 'FULLNAME',
	COUNT(ALL O.EMPLOYEEID) AS 'QUANTITY'
FROM DBO.ORDERS AS O
GROUP BY (O.EMPLOYEEID)
ORDER BY 'Quantity' DESC;