USE NORTHWIND;
GO
SELECT O.ORDERID AS 'ORDER NUMBER', 
	CASE 
		WHEN O.SHIPPEDDATE IS NULL THEN 'NOT SHIPPED'
		else CONVERT(VARCHAR, O.ShippedDate, 6)
	END AS 'SHIPPED DATE' 
FROM DBO.ORDERS AS O
WHERE O.SHIPPEDDATE IS NULL OR O.SHIPPEDDATE >= CONVERT(DATETIME, '1998-05-06');

--dghsagdhasghfagshjfgasj