USE NORTHWIND;
GO
DECLARE @DATE INT = 1998;

SELECT 
		(SELECT CONCAT(E.LASTNAME, E.FIRSTNAME) 
		FROM DBO.EMPLOYEES AS E
		WHERE E.EMPLOYEEID = O.EMPLOYEEID) AS 'EMPLOYEES', 
		COUNT(O.ORDERID) AS 'QUANTITY OF ORDERS',
		O.CUSTOMERID AS 'CUSTOMERS'
FROM DBO.ORDERS AS O
WHERE DATEPART(YEAR, O.ORDERDATE) = @DATE
GROUP BY O.EMPLOYEEID, O.CUSTOMERID;